2.2 Tokenizing text


In [1]:
import os #working with files on device
import urllib.request # downloading things from the internet
file_path  = "the-verdict.txt"

In [2]:
with open(file_path, "r") as f:
    raw_text = f.read()

In [3]:
raw_text

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn\'s "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?\n\nWell!--even 

In [4]:
len(raw_text)

20479

In [5]:
import re

text = "Hello World. This is a test. Hello again!"
result = re.split(r'([,.]|\s)', text)
print(result)

['Hello', ' ', 'World', '.', '', ' ', 'This', ' ', 'is', ' ', 'a', ' ', 'test', '.', '', ' ', 'Hello', ' ', 'again!']


In [6]:
result = [item for item in result if item.strip()]
print(result)

['Hello', 'World', '.', 'This', 'is', 'a', 'test', '.', 'Hello', 'again!']


In [7]:
text = "Hello, world. Is this-- a test?"

result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
result = [item.strip() for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']


In [8]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(preprocessed[:30])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


In [9]:
len(preprocessed)

4690

2.3 Converting tokens into token IDs

In [10]:
all_words = sorted(set(preprocessed)) # sorted list of unique words
print(all_words[:30])
vocab_size = len(all_words)
print(vocab_size)

['!', '"', "'", '(', ')', ',', '--', '.', ':', ';', '?', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be', 'Begin', 'Burlington', 'But', 'By', 'Carlo', 'Chicago', 'Claude', 'Come', 'Croft', 'Destroyed']
1130


In [11]:
vocab = {token: integer for integer,token in enumerate(all_words)}
print(vocab)

{'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Chicago': 25, 'Claude': 26, 'Come': 27, 'Croft': 28, 'Destroyed': 29, 'Devonshire': 30, 'Don': 31, 'Dubarry': 32, 'Emperors': 33, 'Florence': 34, 'For': 35, 'Gallery': 36, 'Gideon': 37, 'Gisburn': 38, 'Gisburns': 39, 'Grafton': 40, 'Greek': 41, 'Grindle': 42, 'Grindles': 43, 'HAD': 44, 'Had': 45, 'Hang': 46, 'Has': 47, 'He': 48, 'Her': 49, 'Hermia': 50, 'His': 51, 'How': 52, 'I': 53, 'If': 54, 'In': 55, 'It': 56, 'Jack': 57, 'Jove': 58, 'Just': 59, 'Lord': 60, 'Made': 61, 'Miss': 62, 'Money': 63, 'Monte': 64, 'Moon-dancers': 65, 'Mr': 66, 'Mrs': 67, 'My': 68, 'Never': 69, 'No': 70, 'Now': 71, 'Nutley': 72, 'Of': 73, 'Oh': 74, 'On': 75, 'Once': 76, 'Only': 77, 'Or': 78, 'Perhaps': 79, 'Poor': 80, 'Professional': 81, 'Renaissance': 82, 'Ri

In [12]:
vocab["What"]

109

In [13]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}
    def encode(self,text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'([,.:;?_!"()\']|--|\s)', r'\1', text)
        return text

In [14]:
text = "I am a genius. What are you?"
tokenizer = SimpleTokenizerV1(vocab)
ids = tokenizer.encode(text)
reconstructed = tokenizer.decode(ids)
reconstructed


'I am a genius . What are you ?'

2.4 Adding special context tokens

In [15]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])
print(all_tokens[:30])
vocab = {token: integer for integer,token in enumerate(all_tokens)}
print(len(vocab.items()))


['!', '"', "'", '(', ')', ',', '--', '.', ':', ';', '?', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be', 'Begin', 'Burlington', 'But', 'By', 'Carlo', 'Chicago', 'Claude', 'Come', 'Croft', 'Destroyed']
1132


In [16]:
for i,item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [17]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}
    def encode(self,text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [item if item in self.str_to_int else "<|unk|>" for item in preprocessed]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'([,.:;?_!"()\']|--|\s)', r'\1', text)
        return text

In [18]:
tokenizer = SimpleTokenizerV2(vocab)
text = "Hello, my dog is cute"
tokenizer.encode(text)

[1131, 5, 697, 1131, 584, 1131]

In [19]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|> , my <|unk|> is <|unk|>'

2.5 Byte pair encoding

In [20]:
import tiktoken

In [21]:
tiktoken.__version__

'0.12.0'

In [22]:
tokenizer = tiktoken.get_encoding("gpt2")

In [23]:
tokenizer.encode("Hello, my dog is cute. pradhyumna")

[15496, 11, 616, 3290, 318, 13779, 13, 778, 324, 12114, 388, 2616]

In [24]:
tokenizer.decode(tokenizer.encode("Hello, my dog is cute. pradhyumna"))

'Hello, my dog is cute. pradhyumna'

2.6 Data sampling with sliding window

In [25]:
enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [26]:
enc_sample = enc_text[50:]

In [27]:
enc_sample

[290,
 4920,
 2241,
 287,
 257,
 4489,
 64,
 319,
 262,
 34686,
 41976,
 13,
 357,
 10915,
 314,
 2138,
 1807,
 340,
 561,
 423,
 587,
 10598,
 393,
 28537,
 2014,
 198,
 198,
 1,
 464,
 6001,
 286,
 465,
 13476,
 1,
 438,
 5562,
 373,
 644,
 262,
 1466,
 1444,
 340,
 13,
 314,
 460,
 3285,
 9074,
 13,
 46606,
 536,
 5469,
 438,
 14363,
 938,
 4842,
 1650,
 353,
 438,
 2934,
 489,
 3255,
 465,
 48422,
 540,
 450,
 67,
 3299,
 13,
 366,
 5189,
 1781,
 340,
 338,
 1016,
 284,
 3758,
 262,
 1988,
 286,
 616,
 4286,
 705,
 1014,
 510,
 26,
 475,
 314,
 836,
 470,
 892,
 286,
 326,
 11,
 1770,
 13,
 8759,
 2763,
 438,
 1169,
 2994,
 284,
 943,
 17034,
 318,
 477,
 314,
 892,
 286,
 526,
 383,
 1573,
 11,
 319,
 9074,
 13,
 536,
 5469,
 338,
 11914,
 11,
 33096,
 663,
 4808,
 3808,
 62,
 355,
 996,
 484,
 547,
 12548,
 287,
 281,
 13079,
 410,
 12523,
 286,
 22353,
 13,
 843,
 340,
 373,
 407,
 691,
 262,
 9074,
 13,
 536,
 48819,
 508,
 25722,
 276,
 13,
 11161,
 407,
 262,
 40123,
 18113,


In [28]:
tokenizer.decode(enc_sample)

' and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn\'s "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?\n\nWell!--even through the prism of Hermia\'s tears I felt able to face the fact with equanimity. Poor Jack Gisburn! The women had made him--it was fitting that they should mourn him. Among his own sex fewer regrets were heard,

In [29]:
context_size = 4

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

In [30]:
print(context_size)

4


In [31]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    target = enc_sample[i]
    print(context, "---->", target)

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257


In [32]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    target = enc_sample[i]
    print(tokenizer.decode(context), "---->", tokenizer.decode([target]))#look at target its a list 

 and ---->  established
 and established ---->  himself
 and established himself ---->  in
 and established himself in ---->  a


In [33]:
import torch

In [34]:
torch.__version__

'2.10.0'

In [35]:
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        #tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        #Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids)-max_length, stride):
            input_chunk = token_ids[i:i+max_length]
            target_chunk = token_ids[i+1:i+1+max_length]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))
        
    def __len__(self):
        return len(self.input_ids)
    
    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]
    

### Linking the parameters to the GPT‑2 tokenizer

In your `create_dataloader_v1`, GPT‑2’s tokenizer is used here:

```python
tokenizer = tiktoken.get_encoding("gpt2")
token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
```

So all parameters operate on this **list of GPT‑2 token IDs** (`token_ids`).

---

### Minimal numeric example (with fake GPT‑2 IDs)

Assume GPT‑2 gives you:

```python
token_ids = [10, 20, 30, 40, 50, 60, 70]   # pretend these are GPT-2 tokens
```

Now call:

```python
dataloader = create_dataloader_v1(
    txt=...,         # gives token_ids above
    batch_size=2,
    max_length=4,
    stride=2,
    shuffle=False,
    drop_last=True,
    num_workers=0,
)
```

#### 1. `max_length` – how many GPT‑2 tokens per sequence

Inside `GPTDatasetV1`:

```python
for i in range(0, len(token_ids) - max_length, stride):
    input_chunk  = token_ids[i : i + max_length]
    target_chunk = token_ids[i + 1 : i + max_length + 1]
```

With `max_length = 4` and `stride = 2`:

- `len(token_ids) = 7`, so `range(0, 7 - 4, 2) = range(0, 3, 2) → i = 0, 2`

i = 0:
- `input_chunk  = [10, 20, 30, 40]`  (length 4 → `max_length`)
- `target_chunk = [20, 30, 40, 50]`  (shifted by 1)

i = 2:
- `input_chunk  = [30, 40, 50, 60]`
- `target_chunk = [40, 50, 60, 70]`

So **dataset has 2 items**, each item is:
- inputs:  4 GPT‑2 tokens  
- targets: 4 GPT‑2 tokens (next‑token labels)

**`max_length` = 4** → every sample is a sequence of 4 GPT‑2 tokens.

---

#### 2. `stride` – how far you slide the GPT‑2 window

Above we used `stride = 2`, so we advanced 2 tokens each time (`i = 0, 2, ...`).

If we used `stride = 1` instead:

- `range(0, 7 - 4, 1) = range(0, 3, 1) → i = 0, 1, 2`

You’d get 3 samples (more overlap):

- i = 0: `[10, 20, 30, 40]`
- i = 1: `[20, 30, 40, 50]`
- i = 2: `[30, 40, 50, 60]`

**Smaller stride = more overlapping GPT‑2 sequences, more training examples.**

---

#### 3. `batch_size` – how many sequences per batch

We have 2 dataset items and `batch_size = 2`, so the `DataLoader` collects them into one batch:

```python
inputs  → shape [2, 4]  # 2 sequences, each 4 GPT‑2 tokens
targets → shape [2, 4]
```

If `batch_size = 1`, you’d get 2 batches, each of shape `[1, 4]`.

**So in GPT‑2 terms: one batch = `batch_size` rows of token IDs, each row length = `max_length`.**

---

#### 4. `shuffle`

- `shuffle=False` → dataset order is as created: first window, second window, etc.
- `shuffle=True`  → the order of samples is randomized **before** batching (but each sample is still a GPT‑2 sequence of length `max_length`).

---

#### 5. `drop_last`

Imagine you had 5 samples and `batch_size=2`:

- Batches without `drop_last`:
  - Batch 1: 2 samples
  - Batch 2: 2 samples
  - Batch 3: 1 sample

- With `drop_last=True`, that last 1‑sample batch is **dropped**.

This doesn’t change tokens, just whether the final smaller batch is kept.

---

#### 6. `num_workers`

- `0` → load data in the main process (simplest; fine here).
- `>0` → use background worker processes to prepare batches faster (useful for large datasets).

---

If you’d like, we can plug in your actual `raw_text` and specific values (e.g. `max_length=4`, `stride=1`) and I can walk you through the **exact first 2–3 batches** in terms of GPT‑2 token IDs and decoded text.

In [36]:
from torch.utils.data import Dataset, DataLoader
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [37]:
dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length=4, stride=4, shuffle=False)


In [38]:
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)


[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [39]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[1807, 3619,  402,  271]]), tensor([[ 3619,   402,   271, 10899]])]


In [40]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print(inputs)
print(targets)

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


2.7 Creating token embeddings

In [41]:
input_ids = torch.tensor([2,3,5,1])

In [42]:
vocab_size = 6
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [43]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [44]:
vocab_size = tokenizer.n_vocab
output_dim = 256
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [45]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035,  ...,  1.3337,  0.0771, -0.0522],
        [ 0.2386,  0.1411, -1.3354,  ..., -0.0315, -1.0640,  0.9417],
        [-1.3152, -0.0677, -0.1350,  ..., -0.3181, -1.3936,  0.5226],
        ...,
        [ 0.5871, -0.0572, -1.1628,  ..., -0.6887, -0.7364,  0.4479],
        [ 0.4438,  0.7411,  1.1263,  ...,  1.2091,  0.6781,  0.3331],
        [-0.2537,  0.1446,  0.7203,  ..., -0.2134,  0.2144,  0.3006]],
       requires_grad=True)


In [46]:
len(embedding_layer.weight)

50257

2.8 Encodeing word positions

In [47]:
vocab_size = tokenizer.n_vocab
output_dim = 256
torch.manual_seed(123)
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [48]:
max_length = 4
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=max_length, stride=4, shuffle=False)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs: ",inputs)
print("Targets: ",targets)

Inputs:  tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Targets:  tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [49]:
token_embeddings = token_embedding_layer(inputs)

In [50]:
token_embeddings.shape

torch.Size([8, 4, 256])

In [51]:
token_embeddings[0, 0]
#-6.3964e-02

tensor([-6.3964e-02,  3.3174e-01,  1.0698e-01, -1.4281e-01, -3.0141e-01,
        -6.3647e-01, -2.2577e+00,  8.0754e-01,  1.2420e+00, -7.9977e-01,
         1.3265e+00, -1.3640e+00, -1.4752e+00, -1.0095e-01, -1.5406e+00,
        -9.0417e-01, -1.2689e-01,  9.2805e-01,  5.6544e-01, -1.8898e-01,
        -1.2679e-01,  4.5306e-01, -7.6017e-01, -1.0059e+00, -9.2078e-01,
         8.7217e-01,  1.8234e+00, -1.9416e+00,  1.0657e+00,  3.9532e-01,
         5.7309e-01, -7.7677e-01, -1.3191e+00, -6.6007e-01,  4.9130e-01,
         1.1239e+00,  1.4588e+00, -3.6530e-01, -4.0372e-02,  1.9042e-01,
        -1.1572e+00, -1.1329e+00,  2.7644e-01,  6.3706e-01, -1.5947e+00,
        -2.6210e-02, -1.4804e+00, -1.0301e+00, -1.3259e+00, -8.9009e-01,
         1.8119e+00,  1.9705e+00,  1.6373e-01, -5.1866e-01,  5.2069e-01,
        -1.0986e+00,  1.3451e+00, -2.5956e-01,  1.2858e+00, -1.9670e+00,
         9.2041e-02,  4.5699e-01, -1.4753e+00, -4.4934e-01,  1.8373e+00,
        -1.1507e+00, -6.0601e-01, -5.3533e-01, -2.9

In [52]:
#position embedding layer

context_length = max_length

pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [53]:
torch.arange(max_length)

tensor([0, 1, 2, 3])

In [54]:
pos_embedding_layer.weight

Parameter containing:
tensor([[-1.4150, -0.3142,  0.2827,  ...,  0.8155, -0.1085, -1.1927],
        [-1.9800,  0.0610, -0.0494,  ..., -0.6422,  0.5716, -1.1329],
        [ 1.0052,  1.7802,  1.2652,  ..., -1.1619, -0.1109,  1.0411],
        [ 0.3760, -0.3758, -0.0484,  ...,  0.1080,  0.3852,  1.0876]],
       requires_grad=True)

In [55]:
pos_embedding_layer(torch.arange(max_length))

tensor([[-1.4150, -0.3142,  0.2827,  ...,  0.8155, -0.1085, -1.1927],
        [-1.9800,  0.0610, -0.0494,  ..., -0.6422,  0.5716, -1.1329],
        [ 1.0052,  1.7802,  1.2652,  ..., -1.1619, -0.1109,  1.0411],
        [ 0.3760, -0.3758, -0.0484,  ...,  0.1080,  0.3852,  1.0876]],
       grad_fn=<EmbeddingBackward0>)

In [56]:
pos_embeddings = pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [57]:
token_embeddings.shape

torch.Size([8, 4, 256])

In [58]:
imput_embeddings = token_embeddings+pos_embeddings

In [59]:
imput_embeddings

tensor([[[-1.4789e+00,  1.7579e-02,  3.8972e-01,  ...,  1.3504e+00,
          -9.1092e-01, -3.5165e+00],
         [-2.3324e+00,  4.1186e-01,  9.3785e-01,  ..., -2.4888e+00,
          -1.1318e+00, -8.1060e-01],
         [ 2.0069e+00,  2.7101e+00,  1.8624e-03,  ..., -2.3875e+00,
           1.0070e+00,  1.1753e+00],
         [ 1.1756e+00,  1.9079e+00, -7.0086e-01,  ..., -1.0136e+00,
           8.5575e-01,  1.2408e+00]],

        [[-1.5232e+00, -1.5865e+00, -9.3895e-01,  ..., -1.0444e-01,
           1.8989e+00, -2.6065e+00],
         [-2.2227e+00,  9.7547e-01,  1.0391e+00,  ..., -1.5073e+00,
           4.0985e+00, -4.1040e-01],
         [ 4.6181e-01,  3.4006e+00,  2.4874e+00,  ..., -4.8047e-01,
          -1.5141e+00,  1.1903e+00],
         [ 2.5676e-02, -1.3083e+00, -1.3384e+00,  ..., -1.3900e+00,
           5.2514e-01,  1.4606e+00]],

        [[-1.3473e+00, -1.3899e+00,  4.1981e-01,  ...,  4.2434e-01,
          -1.2059e+00, -4.3363e-01],
         [-3.2361e+00,  3.7899e-01, -2.8912e-02,  .